# Generated by Django 3.1.4 on 2021-04-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('media', models.FileField(blank=True, default='', upload_to='posts')),
                ('media_type', models.CharField(blank=True, choices=[('link', 'link'), ('video', 'video'), ('image', 'image'), ('', 'blank')], default='', max_length=10)),
                ('link', models.TextField(blank=True, default='')),
            ],
        ),
    ]
