# Generated by Django 3.1.4 on 2021-04-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_link_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_short',
            field=models.TextField(blank=True, default=''),
        ),
    ]
