# Generated by Django 3.1.4 on 2021-05-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0005_auto_20210512_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='password',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='self_destruct',
        ),
    ]
