# Generated by Django 3.1.4 on 2021-05-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0009_auto_20210525_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='authenticate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
