# Generated by Django 3.1.4 on 2021-07-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0012_blog_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='page',
            field=models.IntegerField(choices=[(1, 'blog'), (2, 'project')], default=1),
            preserve_default=False,
        ),
    ]
