# Generated by Django 3.1.4 on 2021-08-11 11:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0013_blog_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='me.blog')),
                ('difficulty', models.TextField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Short', 'Short')])),
                ('coolness', models.FloatField()),
                ('projectStart', models.DateField()),
                ('projectEnd', models.DateField()),
                ('link', models.TextField(blank=True, default='')),
            ],
            bases=('me.blog',),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='page',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='shares',
        ),
        migrations.AddField(
            model_name='blog',
            name='logo',
            field=models.ImageField(default='null', upload_to='projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tagline',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
