# Generated by Django 3.1.4 on 2021-08-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0014_auto_20210811_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='route',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
