# Generated by Django 3.1.4 on 2021-08-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0015_auto_20210812_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tech_stack')),
                ('name', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.ManyToManyField(to='me.TechStack'),
        ),
    ]
