# Generated by Django 3.1.4 on 2021-12-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0016_auto_20210823_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Christmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('password', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
    ]
