# Generated by Django 3.1.4 on 2022-01-02 02:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0017_christmas'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='quick_blog')),
            ],
        ),
        migrations.CreateModel(
            name='QuickSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'image'), ('link', 'link'), ('text', 'text')], max_length=256)),
                ('value', models.TextField()),
                ('header', models.CharField(max_length=256)),
                ('section_id', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='me.quickblog')),
            ],
        ),
    ]
