# Generated by Django 3.1.4 on 2022-01-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0018_quickblog_quicksection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksection',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
