# Generated by Django 3.1.4 on 2022-01-02 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0019_auto_20220101_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksection',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='me.quickblog'),
        ),
        migrations.AlterField(
            model_name='quicksection',
            name='header',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='quicksection',
            name='value',
            field=models.TextField(),
        ),
    ]
