# Generated by Django 3.1.4 on 2022-02-23 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0020_auto_20220101_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 12, 48, 34, 747525, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='quickblog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
