# Generated by Django 3.1.4 on 2022-02-23 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0021_auto_20220223_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickblog',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quickblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 12, 56, 18, 314359, tzinfo=utc)),
        ),
    ]
