# Generated by Django 3.1.4 on 2022-02-23 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0022_auto_20220223_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickblog',
            name='link',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='quickblog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
