# Generated by Django 3.1.4 on 2022-04-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0023_auto_20220223_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlb',
            name='stadium',
            field=models.BooleanField(default=False),
        ),
    ]
