# Generated by Django 3.1.4 on 2022-04-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0024_mlb_stadium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlb',
            name='stadium',
        ),
        migrations.AddField(
            model_name='last',
            name='stadium',
            field=models.BooleanField(default=False),
        ),
    ]
